wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 100
model:
  desc: null
  value: grid
feature_num:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720085934
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.17.4
      8:
      - 3
      - 5
      13: windows-amd64
